const swaggerJsdoc = require('swagger-jsdoc');
const definition = require('./swagger.json');

console.log(definition);
const swaggerDefinition = {
  // Template can be found here: https://swagger.io/specification/#infoObject
  openapi: '3.0.0',
  info: {
    description: 'Test API with autogenerated swagger doc',
    swagger: '2.0',
    title: 'Node, Express, Mongo Boilerplate API',
    version: '1.0.0'
  }
  ,
  servers: [
    {
      url: 'http://localhost:3000',
      description: 'Development server'
    }
  ],
  host: 'localhost:3000'
};

const options = {
  swaggerDefinition,
  // List of files to be processes. You can also set globs './routes/*.js' or mention each rout file comma separated.
  apis: ['api/routes/user.js']

};


const specs = swaggerJsdoc(options);
module.exports = specs;

